### PR TITLE
Adds AppVeyor integration

### PR DESCRIPTION
**Pull request by ignacio**
Adds AppVeyor integration, so each commit is built with Lua 5.1.5, 5.2.4 and 5.3.1 on 32 and 64 bits, using Visual Studio 2015, 2013 and 2012.

Visual Studio 2010 and 2008 are not directly supported because it seems the versions available on AppVeyor do not support 64 bit builds.
Even though the 32 buit builds work fine, in order to simplify the matrix, we don't build with those compilers for the time being.

### CODE REVIEW

**Comment by ignacio** [comment]
You can take a look at the resulting build matrix [here](https://ci.appveyor.com/project/ignacio/luawinmake).

**Comment by ignacio** [comment]
By the way, I left the part about uploading artifacts commented because earlier today it was timing out and making the build fail. If you want, the result of compiling in each configuration is zipped and stored.

**Comment by ignacio** [comment]
Ah, if you've already enabled the integration with appveyor, I could send a PR to add a badge in the readme.

**Comment by Tieske** [comment]
That would be cool. I enabled it, but it seems to fail. Have to find some time to look at it.

**Comment by ignacio** [comment]
Great. Will do that later.
Took a look at the fails. Since all the configurations that fail are those that involve VS 2015, I'd presume that it is because the jobs are not being run on the new "all in one" infrastructure.
You may want to hit the "New Build" button to see if it goes away.

I also could check the "launcher" file exists before running and print a better error message. It's just that it never happened to me.

**Comment by Tieske** [comment]
This is my first encounter with AppVeyor. What do you mean with the "all in one" infrastructure?

And which file do you consider to be the "launcher"?

As they fail very quickly, my guess is that the "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" file simply isn't available.

**Comment by ignacio** [comment]
Oh, sorry. Until recently, on AppVeyor you needed to choose which OS image you would be using. Each image would have Windows plus certain software on it. That software could vary among different images. For instance, Visual Studio 2015 would be only available on a certain image, MinGW would be on a different one, etc.

At the end of June they [announced a new environment](http://www.appveyor.com/blog) were MinGW and Visual Studio 2015 would be also available in the "default" image. Plus, the new environment is much faster and jobs start sooner.

As mentioned in that blog post, they are migrating existing users to the new environment in batches. Currently, it seems that you are running on the old infrastructure. That's why the builds with VS 2015 are failing (it is not installed there, as you have guessed).

I think I just got lucky and my jobs are running on this new environment (and the difference in speed is really noticeable, take a [look here](https://ci.appveyor.com/project/ignacio/luawinmake), each job takes less than 20 seconds on average). 

By launcher I meant `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat`. The batch file you need to call to have the dev environment properly configured to be used in the command line.

Is this any clearer?

**Comment by Tieske** [comment]
thanks for the education :+1:

**Pull request merged**
